* Notes <2017-07-13 Thu> UTI 

  While the SEC factual findings and legal conclusions dealt only with the invoicing delays in the US 
that caused the reslting liq crisis in oct / nov 2013, the SEC's order plaintiffs allegations that defendants knew 
of the one view problems during that portion of the class period  (Oct 2013 - Feb 2013)


  Moreover, the SEC's findings of def. knowledge further supports plaintiffs allegations that def had knowledge of the earlier 
1 view problems that occurred where 1 view was implemented before US implementations in 2013.


  While defendants point out that the SEC's order does not mention the inadequacies of UTI's internal controls...
Plantiffs alledged that defendants issued numerous materially false or misleading statements, of which 
misrepresentations regarding UTI'S internal controls were just one.  Indeed, Plaintiffs also alleged that 
defendants issued false or misleading statements regarding the effectiveness of the 1 view oracle systems, and their
ability to 

Defendants largely concede their knowledge of UTI's internal control problems.  The district court found that plaintiffs alleged scienter
for UTI's internal control mistatements and defendants largely concede this.

Contrary to defendants assertions, plaintiffs explciitly plead that defendants mistatements violated item 303.  Moreover, the standards
are similar. [Address defendants intent to deceive language]

* Birthday checklist

** DONE Figure out what day her birthday and valentines are
+ <2021-02-14 Sun> Valentines Day
+ <2021-02-15 Mon> Birthday
** DONE Clear a space in your closet to stash presents
   DEADLINE: <2021-01-27 Wed>
** DONE Get Chocolates (good ones)
   DEADLINE: <2021-01-27 Wed>
** DONE Get Grape Nuts
   DEADLINE: <2021-01-27 Wed>
** DONE Possible Presents   
   DEADLINE: <2021-01-28 Thu>
+ Wines 
+ Cheese
+ Olives 
+ Bread
+ new phone?


