* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=N2lmaWxyNjBjdGVrdnJvb2ExdHZyNzA3bzQgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 7ifilr60ctekvrooa1tvr707o4
  :END:

  <2018-05-30 Wed 14:00-15:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=YzQ0dTZmbGQzdTZudDlkMTk3NWpyMDNsdWsgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: c44u6fld3u6nt9d1975jr03luk
  :END:

  <2018-05-30 Wed 14:00-15:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=cDd2dGw0NWtkdW1kdDRxaTJzMDZ2OXEzNmMgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: p7vtl45kdumdt4qi2s06v9q36c
  :END:

  <2018-05-30 Wed 14:00-15:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=dDBhNGszYjMwajRxMGl1cXMzZGFodDZlMjAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: t0a4k3b30j4q0iuqs3daht6e20
  :END:

  <2018-05-30 Wed 14:00-15:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA1MzFUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180531T130000Z
  :END:

  <2018-05-31 Thu 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=ZTB0djQyZTlsdW0yNHBwODMzNnJzcTh1ZGMgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: e0tv42e9lum24pp8336rsq8udc
  :END:

  <2018-05-31 Thu 15:30-16:30>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Onping Overview and Walkthrough
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/336244511
  :LINK: [[https://www.google.com/calendar/event?eid=bWYwYmt2dG1rZGlxZ3RiYWVsOG4zZmkzZTAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: mf0bkvtmkdiqgtbael8n3fi3e0
  :END:

  <2018-05-31 Thu 15:30-16:30>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/336244511

Or iPhone one-tap :
    US: +16465588665,,336244511#  or +14086380986,,336244511# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 336 244 511
    International numbers available: https://zoom.us/u/bIkfQyaS
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDFUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180601T130000Z
  :END:

  <2018-06-01 Fri 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA2MDFUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180601T160000Z
  :END:

  <2018-06-01 Fri 11:00-12:00>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDJUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180602T130000Z
  :END:

  <2018-06-02 Sat 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDNUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180603T130000Z
  :END:

  <2018-06-03 Sun 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDRUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180604T130000Z
  :END:

  <2018-06-04 Mon 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDVUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180605T130000Z
  :END:

  <2018-06-05 Tue 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDZUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180606T130000Z
  :END:

  <2018-06-06 Wed 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Logan gone
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NWMzbGhmdTcwY3VocHMxYmkwYmRlMDI0cGMgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 5c3lhfu70cuhps1bi0bde024pc
  :END:

  <2018-06-06 Wed 20:00>--<2018-06-12 Tue 18:40>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDdUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180607T130000Z
  :END:

  <2018-06-07 Thu 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Daniel Talking
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NzNrNTEzbnNmaDJydmNkNmtoYjQzNGRscnEgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 73k513nsfh2rvcd6khb434dlrq
  :END:

  <2018-06-07 Thu 10:30-11:30>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDhUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180608T130000Z
  :END:

  <2018-06-08 Fri 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MDlUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180609T130000Z
  :END:

  <2018-06-09 Sat 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Charity
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=Mzh0cTEwaThhNzI3cmxxNWxxcXJyYmpvaG9fMjAxODA2MTAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 38tq10i8a727rlq5lqqrrbjoho_20180610
  :END:

  <2018-06-10 Sun>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTBUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180610T130000Z
  :END:

  <2018-06-10 Sun 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTFUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180611T130000Z
  :END:

  <2018-06-11 Mon 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTJUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180612T130000Z
  :END:

  <2018-06-12 Tue 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTNUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180613T130000Z
  :END:

  <2018-06-13 Wed 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTRUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180614T130000Z
  :END:

  <2018-06-14 Thu 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Orion Introduction
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=Mmh2bzR0amEybWpobHBwNmZydWg0aHQ5dHAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 2hvo4tja2mjhlpp6fruh4ht9tp
  :END:

  <2018-06-14 Thu 13:30-14:30>
* Alex Overview
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NGczZmFqb3BmYW1lczdjdGFma3Z2bjUyZmogc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 4g3fajopfames7ctafkvvn52fj
  :END:

  <2018-06-14 Thu 16:00-17:00>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTVUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180615T130000Z
  :END:

  <2018-06-15 Fri 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA2MTVUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180615T160000Z
  :END:

  <2018-06-15 Fri 11:00-12:00>
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTZUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180616T130000Z
  :END:

  <2018-06-16 Sat 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Rotate Tires
  :PROPERTIES:
  :LOCATION: Freddies Tires
  :LINK: [[https://www.google.com/calendar/event?eid=bDZvYzYwMHM0NmY3anAxN3E4bmRzaWhuZ2tfMjAxODA2MTZUMTcwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: l6oc600s46f7jp17q8ndsihngk_20180616T170000Z
  :END:

  <2018-06-16 Sat 12:00-13:00>

Rotate Brooke's Tires
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTdUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180617T130000Z
  :END:

  <2018-06-17 Sun 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MThUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180618T130000Z
  :END:

  <2018-06-18 Mon 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Plow Field Service Meeting
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/344736287
  :LINK: [[https://www.google.com/calendar/event?eid=djlpaGM2dnNzbmNtOHRjdjM0MmgxOGhpMm9fMjAxODA2MTlUMTMwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: v9ihc6vssncm8tcv342h18hi2o_20180619T130000Z
  :END:

  <2018-06-19 Tue 08:00-09:00>

Hi there, 

Scott Murphy is inviting you to a scheduled Zoom meeting. 

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/344736287

Or iPhone one-tap :
    US: +16465588665,,344736287#  or +14086380986,,344736287# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8665  or +1 408 638 0986 
    Meeting ID: 344 736 287
    International numbers available: https://zoom.us/u/cuKwVAHVC
* Lightning Talks
  :PROPERTIES:
  :LOCATION: StarSpace46, 1141 W Sheridan Ave, Oklahoma City, OK, us, 73106
  :LINK: [[https://www.google.com/calendar/event?eid=XzZ0bG5hcXJsZTVwNmNwYjRkaG1qNHBocGVncG1ncGJlNnNzbW9zMW5jOWkzZ2NiYmNocGplcmJmNjByM2V0amg2MWduOHNyZDY5aDZhcXJhZWtvNjZvcmQ3MWdtZXFwamVwaW5jdDNnY3BsajAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: _6tlnaqrle5p6cpb4dhmj4phpegpmgpbe6ssmos1nc9i3gcbbchpjerbf60r3etjh61gn8srd69h6aqraeko66ord71gmeqpjepinct3gcplj0
  :END:

  <2018-06-19 Tue 11:30-12:30>

To see detailed information for automatically created events like this one, use the official Google Calendar app. https://g.co/calendar

This event was created from an email you received in Gmail. https://mail.google.com/mail?extsrc=cal&plid=ACUX6DMsMI2_fOG6IrUHY9bC1GldyyXUeREqAfs
* Will Taylor Lunch
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=N2huNWwwbW1ianNkZmlydXA5djMwNDFxMnYgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 7hn5l0mmbjsdfirup9v3041q2v
  :END:

  <2018-06-22 Fri 12:15-13:15>
* Mark Knutson
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=MzYwYnVmMGFvZzJpM2d0ZDN1MDZxbXFwdGsgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 360buf0aog2i3gtd3u06qmqptk
  :END:

  <2018-06-26 Tue 09:00-10:00>
* Type Systems
  :PROPERTIES:
  :LOCATION: StarSpace 46, 1141 W Sheridan Ave, Oklahoma City, OK, us, 73106
  :LINK: [[https://www.google.com/calendar/event?eid=XzZ0bG5hcXJsZTVwNmNwYjRkaG1qNHBocGVobG04c2JiZTlxamdvamVjaGozY2ViYmU1bjM4ZDFpNnNwNzJxaHBlZ3M2YXEzbWRsaTZldGpqZWhtNzhvOWdjZ3E3Y29yaWQ1bWphcWpsZW9zNmUgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: _6tlnaqrle5p6cpb4dhmj4phpehlm8sbbe9qjgojechj3cebbe5n38d1i6sp72qhpegs6aq3mdli6etjjehm78o9gcgq7corid5mjaqjleos6e
  :END:

  <2018-06-26 Tue 11:30-12:30>

To see detailed information for automatically created events like this one, use the official Google Calendar app. https://g.co/calendar

This event was created from an email you received in Gmail. https://mail.google.com/mail?extsrc=cal&plid=ACUX6DMfERJNXi5ROFgIScWNBr8t2n7aSMTgfvE
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA2MjlUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180629T160000Z
  :END:

  <2018-06-29 Fri 11:00-12:00>
* Pull data for valiant
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=cG90dTNxNXRkaG00NDljMWo3N2s2ODExZDRfMjAxODA2MzBUMTkwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: potu3q5tdhm449c1j77k6811d4_20180630T190000Z
  :END:

  <2018-06-30 Sat 14:00-15:00>
* Stay at Premier RV Resort
  :PROPERTIES:
  :LOCATION: 33022 Van Duyn Rd, Coburg, OR 97408, United States
  :LINK: [[https://www.google.com/calendar/event?eid=XzZ0bG5hcXJsZTVwNmNwYjRkaG1qNHBocGVoaDdjZTNjY2dzNm1yMzFja3I3NmRqN2Vjb2ppcjMyZXBobTZyYmJjZ29uOGNyajZkbW1vcTNjYzltbmN0M2dkZG03MG9qYWU5aDNnZTMzZHNzMzAgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: _6tlnaqrle5p6cpb4dhmj4phpehh7ce3ccgs6mr31ckr76dj7ecojir32ephm6rbbcgon8crj6dmmoq3cc9mnct3gddm70ojae9h3ge33dss30
  :END:

  <2018-07-07 Sat>--<2018-07-09 Mon>

To see detailed information for automatically created events like this one, use the official Google Calendar app. https://g.co/calendar

This event was created from an email you received in Gmail. https://mail.google.com/mail?extsrc=cal&plid=ACUX6DPzPJgZWM4e8mwcKB0yYe7s_yLejuCzEjw
* Charity
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=Mzh0cTEwaThhNzI3cmxxNWxxcXJyYmpvaG9fMjAxODA3MDggc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 38tq10i8a727rlq5lqqrrbjoho_20180708
  :END:

  <2018-07-08 Sun>
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA3MTNUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180713T160000Z
  :END:

  <2018-07-13 Fri 11:00-12:00>
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA3MjdUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180727T160000Z
  :END:

  <2018-07-27 Fri 11:00-12:00>
* Pull data for valiant
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=cG90dTNxNXRkaG00NDljMWo3N2s2ODExZDRfMjAxODA3MzBUMTkwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: potu3q5tdhm449c1j77k6811d4_20180730T190000Z
  :END:

  <2018-07-30 Mon 14:00-15:00>
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA4MTBUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180810T160000Z
  :END:

  <2018-08-10 Fri 11:00-12:00>
* Charity
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=Mzh0cTEwaThhNzI3cmxxNWxxcXJyYmpvaG9fMjAxODA4MTIgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 38tq10i8a727rlq5lqqrrbjoho_20180812
  :END:

  <2018-08-12 Sun>
* Oil Change
  :PROPERTIES:
  :LOCATION: House
  :LINK: [[https://www.google.com/calendar/event?eid=ZmJodHFmM2tuOHFjNjI5NjBxamRybnZnYWdfMjAxODA4MTRUMTEwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: fbhtqf3kn8qc62960qjdrnvgag_20180814T110000Z
  :END:

  <2018-08-14 Tue 06:00-07:00>
* Beat the heat
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NmY5dHVydWhxbHFnNzQyMHFqbjIxbTNuamsgc2NvdHRtdXJwaHkwOUBt][Go to gcal web page]]
  :ID: 6f9turuhqlqg7420qjn21m3njk
  :END:

  <2018-08-17 Fri>--<2018-08-19 Sun>
* Marketing strategy and review
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=bWtzMWxycjh0ZHZtOTA1Ym5nOWc4djRuZW9fMjAxODA4MjRUMTYwMDAwWiBzY290dG11cnBoeTA5QG0][Go to gcal web page]]
  :ID: mks1lrr8tdvm905bng9g8v4neo_20180824T160000Z
  :END:

  <2018-08-24 Fri 11:00-12:00>
